Mvc Consume/Models/Amigo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Amigos_Api.Models
{
    public class Amigo
    {
        
        public int AmigoId { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public DateTime Aniversario { get; set; }
        public List<Amigo> Amigos { get; set; }
        public string PaisOrigem { get; set; }
        public string EstadoOrigem { get; set; }
        public string ImagemAmigo { get; set; }
    }
}

Mvc Consume/Controllers/AmigosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Amigos_Api.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Mvc_Consume.Helper;
using Newtonsoft.Json;

namespace Mvc_Consume.Controllers
{
    public class AmigosController : Controller
    {
        AmigosApi _api = new AmigosApi();

        // GET: AmigosController
        public async Task<ActionResult> Index()
        {
            List<Amigo> amigos = new List<Amigo>();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("api/amigo");

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                amigos = JsonConvert.DeserializeObject<List<Amigo>>(result);
            }

            return View(amigos);
        }

        // GET: AmigosController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var amigo = new List<Amigo>();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/amigo/{id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                amigo = JsonConvert.DeserializeObject<List<Amigo>>(result);
            }
            return View(amigo);
        }

        // GET: AmigosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AmigosController/Create

        [HttpPost]
        public async Task<IActionResult> Create(Amigo Amigo)
        {
            Amigo reciveAmigo = new Amigo();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(Amigo), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync("http://localhost:51427/api/amigo", content))
                {
                    string apiResponse = await
                    response.Content.ReadAsStringAsync();
                    reciveAmigo = JsonConvert.DeserializeObject<Amigo>(apiResponse);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: AmigosController/Edit/5
        // GET: PaisesController/Edit/5
        public ActionResult Edit( )
        {
            return View();
        }

        // POST: AmigosController/Edit/5
        
        [HttpPut("{id}")]
        public async Task<IActionResult> Edit(int id, Amigo amigo)
        {
            Amigo reciveAmigo = new Amigo();

            if (id != amigo.AmigoId)
            {
                return BadRequest();
            }

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(amigo), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("http://localhost:51427/api/amigo/"+$"{id}", content))
                {
                    string apiResponse = await
                    response.Content.ReadAsStringAsync();
                    reciveAmigo = JsonConvert.DeserializeObject<Amigo>(apiResponse);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: AmigosController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var amigo = new Amigo();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.DeleteAsync($"api/amigo/{id}");
            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));
            }

            return View("Index");
        }

        // POST: AmigosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Foto(int id)
        {
            return View();
        }

        //Postar a foto
        [HttpPost]
        public async Task<IActionResult> Foto(IFormFile files, int id)
        {
            var amigo = new Amigo();
            string imagem = files.FileName;

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(imagem), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("http://localhost:51427/api/amigo/imagem" + $"{id}/imagem", content))
                {
                    string apiResponse = await
                    response.Content.ReadAsStringAsync();
                    amigo = JsonConvert.DeserializeObject<Amigo>(apiResponse);
                }
            }

            return RedirectToAction(nameof(Index));

        }
    }

   
   
}

Mvc Consume/Controllers/ImagemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amigos_Api.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;

namespace Mvc_Consume.Controllers
{
    public class ImagemController : Controller
    {
        private readonly IConfiguration _configuration;

        public ImagemController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpPost("{id}")]
        public async Task<IActionResult> Create(int id, IFormFile files)
        {
            //var account = await _userManager.GetUserAsync(this.User);
            // var perfilLogado = await _context.Amigos
            // .FirstAsync(p => p.Usuario.Email == account.Email);

            string dir = id + "/";
            string systemFileName = dir + files.FileName;
            string blobstorageconnection = _configuration.GetValue<string>("blobstorage");


            // Retrieve storage account from connection string.
            CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse(blobstorageconnection);

            // Create the blob client.
            CloudBlobClient blobClient = cloudStorageAccount.CreateCloudBlobClient();

            // Retrieve a reference to a container.
            CloudBlobContainer container = blobClient.GetContainerReference("imagens");

            container.GetDirectoryReference(dir);

            // This also does not make a service call; it only creates a local object.
            CloudBlockBlob blockBlob = container.GetBlockBlobReference(systemFileName);
            await using (var data = files.OpenReadStream())
            {
                await blockBlob.UploadFromStreamAsync(data);
            }
            return View("Views/Amigos/Index");
        }

        [HttpGet]
        public async Task<IActionResult> ShowAllBlobs(int id)
        {
            //var account = await _userManager.GetUserAsync(this.User);
            //var perfilLogado = await _context.Perfis
            //    .FirstAsync(p => p.Usuario.Email == account.Email);

            string dir = id.ToString() + "/";


            string blobstorageconnection =
           _configuration.GetValue<string>("blobstorage");
            CloudStorageAccount cloudStorageAccount =
           CloudStorageAccount.Parse(blobstorageconnection);
            // Create the blob client.
            CloudBlobClient blobClient = cloudStorageAccount.CreateCloudBlobClient();
            CloudBlobContainer container =
           blobClient.GetContainerReference("imagens");
            CloudBlobDirectory dirb =
           container.GetDirectoryReference(dir);
            BlobResultSegment resultSegment = await
           container.ListBlobsSegmentedAsync(string.Empty,
            true, BlobListingDetails.Metadata, 100, null, null, null);

            List<FileData> fileList = new List<FileData>();
            foreach (var blobItem in resultSegment.Results)
            {
                // A flat listing operation returns only blobs, not virtual directories.

                var blob = (CloudBlob)blobItem;
                fileList.Add(new FileData()
                {
                    FileName = blob.Name,
                    FileSize = Math.Round((blob.Properties.Length / 1024f) / 1024f,
               2).ToString(),
                    ModifiedOn =
               DateTime.Parse(blob.Properties.LastModified.ToString()).ToLocalTime().ToString(
               )
                });
            }
            return Ok();
        }
    }
}

Mvc Consume/Views/Amigos/Create.cshtml
@model Amigos_Api.Models.Amigo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Amigo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aniversario" class="control-label"></label>
                <input asp-for="Aniversario" class="form-control" />
                <span asp-validation-for="Aniversario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaisOrigem" class="control-label"></label>
                <input asp-for="PaisOrigem" class="form-control" />
                <span asp-validation-for="PaisOrigem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoOrigem" class="control-label"></label>
                <input asp-for="EstadoOrigem" class="form-control" />
                <span asp-validation-for="EstadoOrigem" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="ImagemAmigo" class="control-label"></label>
                <input asp-for="ImagemAmigo" class="form-control" />
                <span asp-validation-for="ImagemAmigo" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc Consume/Views/Amigos/Details.cshtml
@model Amigos_Api.Models.Amigo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Amigo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AmigoId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AmigoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aniversario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aniversario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaisOrigem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaisOrigem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoOrigem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoOrigem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagemAmigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagemAmigo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.AmigoId }) |
    <a asp-action="Index">Back to List</a>
</div>

Mvc Consume/Views/Amigos/Edit.cshtml
@model Amigos_Api.Models.Amigo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Amigo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aniversario" class="control-label"></label>
                <input asp-for="Aniversario" class="form-control" />
                <span asp-validation-for="Aniversario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaisOrigem" class="control-label"></label>
                <input asp-for="PaisOrigem" class="form-control" />
                <span asp-validation-for="PaisOrigem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstadoOrigem" class="control-label"></label>
                <input asp-for="EstadoOrigem" class="form-control" />
                <span asp-validation-for="EstadoOrigem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagemAmigo" class="control-label"></label>
                <input asp-for="ImagemAmigo" class="form-control" />
                <span asp-validation-for="ImagemAmigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mvc Consume/Views/Amigos/Foto.cshtml
@{
    ViewData["Title"] = "Foto";
}

<div class="row">
    <div class="col-md-6">
        <form method="post" enctype="multipart/form-data" asp-controller="Imagem" asp-action="Create">
            <div class="form-group">
                <label> Select File </label>
                <input class="form-control" name="files" multiple="multiple" type="file" />
            </div>
            <div class="form-group">
                <input class="btn btn-success" type="submit" value="Submit" />
            </div>
        </form>
    </div>
</div>

Mvc Consume/Views/Amigos/Index.cshtml
@model IEnumerable<Amigos_Api.Models.Amigo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AmigoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aniversario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaisOrigem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstadoOrigem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagemAmigo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AmigoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aniversario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaisOrigem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstadoOrigem)
            </td>
            <td>
                <a href="@Html.DisplayFor(modelItem => item.ImagemAmigo)">Imagem</a>               
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.AmigoId  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.AmigoId  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.AmigoId  }) |
                @Html.ActionLink("Foto", "Foto", new { id = item.AmigoId })
            </td>
        </tr>
}
    </tbody>
</table>